### ISSUE TITLE
Emergency Alerts / CodeRED Signup Form

### ISSUE THREAD

**Issue by ghost** [CityOfBoston/Forms#332]
Have been asked to create a new signup form that's a bit more flexible and user friendly. 

Existing Signup:
https://public.coderedweb.com/cne/en-US/BFB5F355FAB8

API Documentation: 
[CodeRED Web API for Contact Groups v3.0 (1) (2).pdf](https://github.com/joshuagee/Forms/files/646469/CodeRED.Web.API.for.Contact.Groups.v3.0.1.2.pdf)

Contact; 

christopher.coakley@boston.gov -- Emergency Management
jmallory@ecnetwork.com -- Code Red

**Comment by joshuagee** [comment]
SeamlessDocs Comment on Integration:

He also recommended that you use our new endpoints. We haven't updated developers.seamlessdocs.com yet, but you can check out our new endpoints here. you'll want to use /v2/submissions .

Example for /v2/submissions:

```curl -k -X POST
    -H "Authorization: api_key=2tafoLR5I3VyXdw signature=2a0d18f49c9538f263f3b1cc9964c40aa346287790b5e3ff8a019d5a7924596" \
    -H "Date: 1478272186" \
    -H "Content-Type: application/json" \
    -d '{
        "formId": "CO15061000010127181",
        "archiveOptions":"OnlyActive",
        "includeFieldOrdering":true,
         "offset": 0,
         "limit":50
        }' \
    https://stage.seamlessdocs.com/api/v2/submissions
```

Returns:

```{
    "totalVisibleSubmissionsForForm": 3,
    "fieldOrdering": [],
    "records": [{
        "submissionId": "AP16111000010276514",
        "modifiedTs": "2016-11-02T20:59:32.734Z",
        "createdTs": "2016-11-02T20:59:30.001Z",
        "submissionData": [{
            "input_name": "plugin_5N5zh4",
            "raw_value": "Cardholder Name: John Smith<br>CC Number: ************4242<br>Amount: 120.00<br>Transaction ID: 40004051503<br>Authorization Code: CYAF66",
            "label": "Pay with Authorize.net",
            "isEncrypted": false,
            "field_map": []
        }],
        "attachments": [],
        "payment": [],
        "submissionPDFUrl": "https://dev-cdn.seamlessdocs.com/form_pdf/201611/Untitled_Form_rxYrfGAMGxr9TeMJ.pdf",
        "isActive": true,
        "totalSigners": 0,
        "totalCompletedSigners": 0
    }]
}
```

The more submissions a given form has, the more records will be present.


Important notes:

Pagination is very different here as it's not done in the same style as the other requests.

Instead of being managed in a "pagination" object, it's a simple, flat, "offset" and "limit" in the original requst.

"archiveOptions" will let you select archived, unarchived, or all submissions using "OnlyActive", "OnlyArchived", or "IncludeAll" respectively

Your engineers can inquire about the API directly to our team at api@seamlessdocs.com .

**Comment by joshuagee** [comment]
Talked with Matt Crist and reviewed APIs. Problem is that there is more than just signup, there's actual form creation. That makes it nontrivial. 

My next steps are tracking actual traffic numbers and signups (What's the drop-off rate).

**Comment by joshuagee** [comment]
We're addressing this by building a custom front-end form. 

Design: https://github.com/CityOfBoston/design-team-workflow/issues/270#issuecomment-293303971
Code: https://github.com/CityOfBoston/boston.gov/issues/583
